Make include file mandatory
The dotsync script now alawys use include for the name of files or
directories to backup. If the include file is missing, the user is
prompted for generating a copy of the sample include file.
Also, add ipython configuration file

diff --git a/dotsync b/dotsync
--- a/dotsync
+++ b/dotsync
@@ -39,16 +39,20 @@ repo_dir=$(dirname "$0")
 include_file="$repo_dir/include"
 
 # List of files/folders to backup
-if [[ -f $include_file ]]
+if [[ ! -r $include_file ]]
 then
-    echo "Using include file"
-    files=$(cat $include_file)
-else
-    files=".vimrc .vim/after/ftplugin
-        .hushlogin .zsh .zshenv .zshrc .zprofile
-        .bash_profile
-        .gitignore_global"
+    echo "Missing include file" >&2
+    read -p "Generate include file using sample and continue? [Y/n]" -n 1 ans
+    case $ans in
+        [Nn])
+            exit;;
+        *)
+            cp sample_include include
+            echo "Copied sample include file"
+            ;;
+    esac
 fi
+files=$(cat $include_file)
 
 # Handle install mode
 if [[ $mode = 'i' ]]
